id: A518C89F0
title: 'Bright Light of the Sun: A Simple Fire Offering Based on a Single Substance'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:39:11.277510
  last_modified_at: 2022-03-01 01:39:11.277516
